### ISSUE TITLE
Many people encounter the same problem when using the portable version of ComfyUI. The issue with the node not showing is unrelated to this repository!

### ISSUE THREAD

**Issue by YG6688-bit** [balazik/ComfyUI-PuLID-Flux#20]
Copy the requirements.txt file inside the python path, after copying this command python.exe -m pip install -r requirements.txt open the cmd and the installation is successful! Pro-tested it works, thanks for sharing!

**Comment by YG6688-bit** [comment]
Copy the requirements.txt file inside the python path, after copying this command python.exe -m pip install -r requirements.txt open the cmd and the installation is successful! Pro-tested it works, thanks for sharing!

**Comment by Netsky1980** [comment]
D:\AI\ComfyUI\ComfyUI\python_embeded>python.exe -m pip install -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt
Collecting facexlib (from -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 1))
  Using cached facexlib-0.3.0-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: insightface in d:\ai\comfyui\comfyui\python_embeded\lib\site-packages (from -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 2)) (0.7.3)
Requirement already satisfied: onnxruntime in d:\ai\comfyui\comfyui\python_embeded\lib\site-packages (from -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 3)) (1.19.2)
Requirement already satisfied: onnxruntime-gpu in d:\ai\comfyui\comfyui\python_embeded\lib\site-packages (from -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 4)) (1.19.2)
Requirement already satisfied: ftfy in d:\ai\comfyui\comfyui\python_embeded\lib\site-packages (from -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 5)) (6.2.3)
Requirement already satisfied: timm in d:\ai\comfyui\comfyui\python_embeded\lib\site-packages (from -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 6)) (0.6.13)
Collecting filterpy (from facexlib->-r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 1))
  Using cached filterpy-1.4.5.zip (177 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lnsyp\AppData\Local\Temp\pip-install-30_ohlg3\filterpy_e40e3668304a43dc8677e9ed9f381bbc\setup.py", line 4, in <module>
          import filterpy
      ModuleNotFoundError: No module named 'filterpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

After following this step, this error occurs. How can I fix this error

**Comment by vootox** [comment]
I have the same errors.

**Comment by vootox** [comment]
> D:\AI\ComfyUI\ComfyUI\python_embeded>python.exe -m pip install -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt Collecting facexlib (from -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 1)) Using cached facexlib-0.3.0-py3-none-any.whl.metadata (4.6 kB) Requirement already satisfied: insightface in d:\ai\comfyui\comfyui\python_embeded\lib\site-packages (from -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 2)) (0.7.3) Requirement already satisfied: onnxruntime in d:\ai\comfyui\comfyui\python_embeded\lib\site-packages (from -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 3)) (1.19.2) Requirement already satisfied: onnxruntime-gpu in d:\ai\comfyui\comfyui\python_embeded\lib\site-packages (from -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 4)) (1.19.2) Requirement already satisfied: ftfy in d:\ai\comfyui\comfyui\python_embeded\lib\site-packages (from -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 5)) (6.2.3) Requirement already satisfied: timm in d:\ai\comfyui\comfyui\python_embeded\lib\site-packages (from -r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 6)) (0.6.13) Collecting filterpy (from facexlib->-r D:\AI\ComfyUI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\requirements.txt (line 1)) Using cached filterpy-1.4.5.zip (177 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [6 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in File "C:\Users\lnsyp\AppData\Local\Temp\pip-install-30_ohlg3\filterpy_e40e3668304a43dc8677e9ed9f381bbc\setup.py", line 4, in import filterpy ModuleNotFoundError: No module named 'filterpy' [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.
> 
> After following this step, this error occurs. How can I fix this error

I have the same errors.

**Comment by vootox** [comment]
Mine is working now:

 https://github-com.translate.goog/cubiq/PuLID_ComfyUI/issues/1?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc
 
Summary of what worked for me

`E:\ComfyUI\Portable_06>.\python_embeded\python.exe -m pip install --use-pep517 facexlib
E:\ComfyUI\Portable_06>.\python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl
E:\ComfyUI\Portable_06>.\python_embeded\python.exe -m pip uninstall onnx onnxruntime
E:\ComfyUI\Portable_06>.\python_embeded\python.exe -m pip install onnx==1.16.2 onnxruntime==1.19.2
E:\ComfyUI\Portable_06>.\python_embeded\python.exe -m pip install onnxruntime-gpu==1.19.2
E:\ComfyUI\Portable_06>.\python_embeded\python.exe -m pip install ftfy
E:\ComfyUI\Portable_06>.\python_embeded\python.exe -m pip install timm
`

Also I had to look up the correct onnxruntime version for my version of CUDA but I've lost that URL

"Why --use-pep517" worked:
[https://github-com.translate.goog/cubiq/PuLID_ComfyUI/issues/1?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc#issuecomment-2124807351](url)

**Comment by HaiyiMei** [comment]
https://github.com/ZHO-ZHO-ZHO/ComfyUI-PuLID-ZHO/issues/6#issuecomment-2102836069

This works for me
