### ISSUE TITLE
PulidFluxInsightFaceLoader FaceAnalysis.__init__() got an unexpected keyword argument 'providers' .help me！！

### ISSUE THREAD

**Issue by xiewci** [balazik/ComfyUI-PuLID-Flux#26]
got prompt
!!! Exception during processing !!! FaceAnalysis.__init__() got an unexpected keyword argument 'providers'
Traceback (most recent call last):
  File "/comfyui/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/comfyui/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/comfyui/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/comfyui/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/comfyui/custom_nodes/ComfyUI-PuLID-Flux/pulidflux.py", line 196, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
TypeError: FaceAnalysis.__init__() got an unexpected keyword argument 'providers'
![image](https://github.com/user-attachments/assets/40b184bd-064c-4c66-9be4-ab928d900176)

**Comment by balazik** [comment]
Hi, @xiewci 
Maybe your **insightface** package is too old, see here: [https://github.com/nosiu/comfyui-instantId-faceswap/issues/6](https://github.com/nosiu/comfyui-instantId-faceswap/issues/6)
I use: insightface==0.7.3 (my env is Python 3.11)

Let me know if updating helped (and please mention the current version that you have now, to help other users that encounter the same issue)

**Comment by kknbytj** [comment]
Same problem with insightface version == 0.2.1, solved by reinstall insightface version == 0.7.3. Thanks. @balazik
