### ISSUE TITLE
(IMPORT FAILED) numpy.dtype size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by mumpischlumpi** [balazik/ComfyUI-PuLID-Flux#42]
For some reason I can't install PuLID-Flux (and the standard PuLID) for the new ComfyUI version (v0.2.4). For 0.2.3 it works well after I install facelib and insightface. Did the same for v0.2.4 (with the correct insightface wheel for the new python version) but it gives me these errors: 
```
File "insightface\\thirdparty\\face3d\\mesh\\cython\\mesh_core_cython.pyx", line 1, in init insightface.thirdparty.face3d.mesh.cython.mesh_core_cython
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

[2024-10-24 17:44:40.955] Cannot import C:\01_AI_TOOLS\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
Full report: 
```
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-24 18:38:20.059485
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\python.exe
** ComfyUI Path: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI
** Log path: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\rgthree-comfy
   2.5 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 64730 MB
pytorch version: 2.5.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\web
C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Impact-Pack (V7.10.6)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
[Impact Pack] Wildcards loading done.
Total VRAM 24564 MB, total RAM 64730 MB
pytorch version: 2.5.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.51.8)
### ComfyUI Revision: 2784 [af8cf79a] | Released on '2024-10-24'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.19 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
Traceback (most recent call last):
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\__init__.py", line 1, in <module>
    from .pulidflux import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\pulidflux.py", line 11, in <module>
    from insightface.app import FaceAnalysis
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
  File "insightface\\thirdparty\\face3d\\mesh\\cython\\mesh_core_cython.pyx", line 1, in init insightface.thirdparty.face3d.mesh.cython.mesh_core_cython
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Cannot import C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Traceback (most recent call last):
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\PuLID_ComfyUI\__init__.py", line 1, in <module>
    from .pulid import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\PuLID_ComfyUI\pulid.py", line 9, in <module>
    from insightface.app import FaceAnalysis
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
  File "insightface\\thirdparty\\face3d\\mesh\\cython\\mesh_core_cython.pyx", line 1, in init insightface.thirdparty.face3d.mesh.cython.mesh_core_cython
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Cannot import C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\PuLID_ComfyUI module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

[rgthree-comfy] Loaded 42 extraordinary nodes. 🎉

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "Art is the lie that enables us to recognize the truth." - Friedrich Nietzsche


Import times for custom nodes:
   0.0 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds (IMPORT FAILED): C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\PuLID_ComfyUI
   0.0 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\sigmas_tools_and_the_golden_scheduler
   0.0 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.2 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.3 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds (IMPORT FAILED): C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
   0.8 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
   1.4 seconds: C:\01_AI_TOOLS\ComfyUI_windows_portable_demo01\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server
```
Thanks for any help on this!

**Comment by BestofthebestinAI** [comment]
you found solution?

**Comment by BestofthebestinAI** [comment]
wtf one year later
