### ISSUE TITLE
Pulid insightface loader error help.

### ISSUE THREAD

**Issue by manosrmd** [balazik/ComfyUI-PuLID-Flux#70]
Im getting this error: I dont know what to do since there are no  other informations. Could somebody help me?

PulidFluxInsightFaceLoader

# ComfyUI Error Report
## Error Details
- **Node ID:** 159
- **Node Type:** PulidFluxInsightFaceLoader
- **Exception Type:** AssertionError
- **Exception Message:** 
## Stack Trace
File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\pulidflux.py", line 252, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

## System Information
- **ComfyUI Version:** v0.3.6
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8589279232
  - **VRAM Free:** 5453242164
  - **Torch VRAM Total:** 1979711488
  - **Torch VRAM Free:** 4841268

## Logs
2024-12-03T02:11:30.835069 - [START] Security scan2024-12-03T02:11:30.835521 - 
2024-12-03T02:11:49.224112 - [DONE] Security scan2024-12-03T02:11:49.224112 - 
2024-12-03T02:11:50.894824 - ## ComfyUI-Manager: installing dependencies done.2024-12-03T02:11:50.894824 - 
2024-12-03T02:11:50.894824 - ** ComfyUI startup time:2024-12-03T02:11:50.894824 -  2024-12-03T02:11:50.895822 - 2024-12-03 02:11:50.8948242024-12-03T02:11:50.895822 - 
2024-12-03T02:11:50.974833 - ** Platform:2024-12-03T02:11:50.974833 -  2024-12-03T02:11:50.974833 - Windows2024-12-03T02:11:50.974833 - 
2024-12-03T02:11:50.974833 - ** Python version:2024-12-03T02:11:50.974833 -  2024-12-03T02:11:50.974833 - 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]2024-12-03T02:11:50.974833 - 
2024-12-03T02:11:50.975831 - ** Python executable:2024-12-03T02:11:50.975831 -  2024-12-03T02:11:50.975831 - D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\python.exe2024-12-03T02:11:50.975831 - 
2024-12-03T02:11:50.975831 - ** ComfyUI Path:2024-12-03T02:11:50.975831 -  2024-12-03T02:11:50.975831 - D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI2024-12-03T02:11:50.975831 - 
2024-12-03T02:11:50.975831 - ** Log path:2024-12-03T02:11:50.975831 -  2024-12-03T02:11:50.976833 - D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\comfyui.log2024-12-03T02:11:50.976833 - 
2024-12-03T02:11:52.570067 - 
Prestartup times for custom nodes:2024-12-03T02:11:52.571067 - 
2024-12-03T02:11:52.571067 -   22.0 seconds:2024-12-03T02:11:52.571067 -  2024-12-03T02:11:52.571067 - D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager2024-12-03T02:11:52.571067 - 
2024-12-03T02:11:52.571067 - 
2024-12-03T02:12:13.183215 - Total VRAM 8191 MB, total RAM 16252 MB
2024-12-03T02:12:13.183215 - pytorch version: 2.5.1+cu124
2024-12-03T02:12:13.184799 - Set vram state to: NORMAL_VRAM
2024-12-03T02:12:13.185805 - Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
2024-12-03T02:12:29.850780 - Using pytorch cross attention
2024-12-03T02:13:14.889089 - [Prompt Server] web root: D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\web
2024-12-03T02:13:24.296334 - ### Loading: ComfyUI-Manager (V2.54)2024-12-03T02:13:24.296334 - 
2024-12-03T02:13:25.261614 - ### ComfyUI Revision: 2876 [8e4118c0] | Released on '2024-12-01'2024-12-03T02:13:25.261614 - 
2024-12-03T02:13:27.223549 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-12-03T02:13:27.223549 - 
2024-12-03T02:13:27.258807 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-12-03T02:13:27.258807 - 
2024-12-03T02:13:27.300374 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-12-03T02:13:27.300374 - 
2024-12-03T02:13:27.351291 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-12-03T02:13:27.352294 - 
2024-12-03T02:13:27.420413 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-12-03T02:13:27.420413 - 
2024-12-03T02:13:35.949033 - D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
2024-12-03T02:13:36.015891 - Please 'pip install xformers'2024-12-03T02:13:36.016946 - 
2024-12-03T02:13:36.017946 - Nvidia APEX normalization not installed, using PyTorch LayerNorm2024-12-03T02:13:36.017946 - 
2024-12-03T02:13:36.660577 - here: D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-tbox2024-12-03T02:13:36.660577 - 
2024-12-03T02:13:38.944218 - Using ckpts path: D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-tbox\..\..\models\annotator2024-12-03T02:13:38.945723 - 
2024-12-03T02:13:38.945723 - Using symlinks: False2024-12-03T02:13:38.945723 - 
2024-12-03T02:13:38.945723 - Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']2024-12-03T02:13:38.945723 - 
2024-12-03T02:13:39.480970 - D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-tbox\src\common.py:37: UserWarning: custom temp dir is too long. Using default
  warnings.warn(f"custom temp dir is too long. Using default")
2024-12-03T02:13:39.502827 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
2024-12-03T02:13:39.502827 - [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2024-12-03T02:13:39.502827 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2024-12-03T02:13:39.582605 - D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\util.py:56: UserWarning: custom temp dir is too long. Using default
  warnings.warn(f"custom temp dir is too long. Using default")
2024-12-03T02:13:39.942311 - 
[36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[92mSuccess![0m2024-12-03T02:13:39.942311 - 
2024-12-03T02:13:40.020838 - 
Import times for custom nodes:
2024-12-03T02:13:40.020838 -    0.0 seconds: D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-12-03T02:13:40.022343 -    0.1 seconds: D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-12-03T02:13:40.022343 -    0.1 seconds: D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-12-03T02:13:40.022343 -    0.2 seconds: D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-12-03T02:13:40.022343 -    1.4 seconds: D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-12-03T02:13:40.022343 -    2.9 seconds: D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-tbox
2024-12-03T02:13:40.022343 -   11.0 seconds: D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
2024-12-03T02:13:40.023344 - 
2024-12-03T02:13:40.028855 - Starting server

2024-12-03T02:13:40.029855 - To see the GUI go to: http://127.0.0.1:8188
2024-12-03T02:13:40.787420 - FETCH DATA from: D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2024-12-03T02:13:40.787420 - 2024-12-03T02:13:40.804095 -  [DONE]2024-12-03T02:13:40.804095 - 
2024-12-03T02:14:05.583414 - got prompt
2024-12-03T02:14:09.722646 - model weight dtype torch.float16, manual cast: None
2024-12-03T02:14:10.469659 - model_type EPS
2024-12-03T02:16:04.709789 - Using pytorch attention in VAE
2024-12-03T02:16:04.731167 - Using pytorch attention in VAE
2024-12-03T02:16:30.536858 - loaded straight to GPU
2024-12-03T02:16:30.537857 - Requested to load BaseModel
2024-12-03T02:16:30.537857 - Loading 1 new model
2024-12-03T02:16:30.554876 - loaded completely 0.0 1639.406135559082 True
2024-12-03T02:16:31.213560 - Requested to load SD1ClipModel
2024-12-03T02:16:31.214559 - Loading 1 new model
2024-12-03T02:16:31.372803 - loaded completely 0.0 235.84423828125 True
2024-12-03T02:16:35.370640 - ----------------------------------------2024-12-03T02:16:35.371722 - 
2024-12-03T02:16:35.371722 - [36mEfficient Loader Models Cache:[0m2024-12-03T02:16:35.371722 - 
2024-12-03T02:16:35.371722 - Ckpt:2024-12-03T02:16:35.371722 - 
2024-12-03T02:16:35.371722 -   [1] realisticVisionV60B1_v51VAE2024-12-03T02:16:35.371722 - 
2024-12-03T02:16:35.905503 - download_path:2024-12-03T02:16:35.905503 -  2024-12-03T02:16:35.905503 - D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\models\insightface\models\antelopev22024-12-03T02:16:35.906508 - 
2024-12-03T02:16:35.920532 - Downloading D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\models\insightface\models\antelopev2.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip...2024-12-03T02:16:35.921550 - 
2024-12-03T02:17:07.755761 - 
100%|██████████████████████████████████████████████████████████████████████▉| 352030/352210 [00:30<00:00, 11387.56KB/s]2024-12-03T02:17:07.769833 - 
100%|███████████████████████████████████████████████████████████████████████| 352210/352210 [00:30<00:00, 11455.50KB/s]2024-12-03T02:17:07.769833 - 
2024-12-03T02:17:12.770426 - !!! Exception during processing !!! 
2024-12-03T02:17:12.865994 - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\pulidflux.py", line 252, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-12-03T02:17:12.879849 - Prompt executed in 187.26 seconds
2024-12-03T02:17:49.766918 - got prompt
2024-12-03T02:17:49.817987 - !!! Exception during processing !!! 
2024-12-03T02:17:49.818987 - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\pulidflux.py", line 252, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-12-03T02:17:49.819982 - Prompt executed in 0.02 seconds
2024-12-03T02:17:54.602437 - got prompt
2024-12-03T02:17:54.650168 - !!! Exception during processing !!! 
2024-12-03T02:17:54.651165 - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\pulidflux.py", line 252, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-12-03T02:17:54.652671 - Prompt executed in 0.02 seconds
2024-12-03T02:18:09.241522 - got prompt
2024-12-03T02:18:09.295270 - !!! Exception during processing !!! 
2024-12-03T02:18:09.296273 - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\pulidflux.py", line 252, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-12-03T02:18:09.298272 - Prompt executed in 0.02 seconds

.

**Comment by hungih** [comment]
https://github.com/deepinsight/insightface/issues/1525
