### ISSUE TITLE
were are nodes? (everything is updated)

### ISSUE THREAD

**Issue by peppepascale** [balazik/ComfyUI-PuLID-Flux#9]
![image](https://github.com/user-attachments/assets/1109fc9b-f10b-4089-bd98-65396fb20123)

**Comment by ohahaps2** [comment]
same red

**Comment by balazik** [comment]
It is possible that you miss some required packages in your python environment.
Look at requirements.txt of this repo. This Node will not install them automatically. You must install them manually. Then will ComfyUI load the nodes correctly.

If you need help how to do it. Just let me know.

**Comment by 2PeteShakur** [comment]
same issue as op, have latest version of comfyui portable and installed the requirements.txt, still same red missing nodes?

**Comment by threeforces** [comment]
Following erros @ Boot:

Traceback (most recent call last):
  File "D:\DEV\COMFY\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\DEV\COMFY\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\__init__.py", line 1, in <module>
    from .pulidflux import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\DEV\COMFY\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\pulidflux.py", line 12, in <module>
    from facexlib.parsing import init_parsing_model
ModuleNotFoundError: No module named 'facexlib'

**Comment by threeforces** [comment]
This fixed it for me: https://github.com/cubiq/PuLID_ComfyUI/issues/23

**Comment by cchance27** [comment]
it literally says whts wrong... 

ModuleNotFoundError: No module named 'facexlib'

pip install facexlib

**Comment by leonviz87** [comment]
I am also facing the same issue with the missing node and i have manually installed PuLID but am not seeing the nodes though.

**Comment by balazik** [comment]
@leonviz87 
I have always the same question, did you install also the Python packages in **requirements.txt** ?

The problem is that I newer know what experience you all have with Python (I don't want to offend anyone) so I rather ask, because 90% of all missing node errors are caused by the missing packages (I even updated the install instructions to reflect the problem).

**Comment by balazik** [comment]
Many people encounter the same problem when using the portable version of ComfyUI. The issue with the node not showing is unrelated to this repository!

It occurs because the portable version has its own Python interpreter. If you run `pip install -r requirements.txt`, it will install the packages in your local Python environment, not in the embedded Python within the portable ComfyUI. You need to navigate to the directory where the embedded Python is located and install the packages from there.

**Comment by YG6688-bit** [comment]
> ![image](https://private-user-images.githubusercontent.com/73500050/372766472-1109fc9b-f10b-4089-bd98-65396fb20123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTYxMjMsIm5iZiI6MTcyODIxNTgyMywicGF0aCI6Ii83MzUwMDA1MC8zNzI3NjY0NzItMTEwOWZjOWItZjEwYi00MDg5LWJkOTgtNjUzOTZmYjIwMTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDExNTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ODU0MmE0NDc0NTViY2E1YmNjNWZhMDg1YWViOTU5MGI1NjQ4MTI4Y2VkODFkYjc4YTg5N2EyM2ZjNDlkMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H51Z9POM4IaCW5Ll5RiC41ww8HZ3-UNbeuRTWmyuKzg)

**Comment by YG6688-bit** [comment]
Copy the requirements.txt file inside the python path, after copying this command python.exe -m pip install -r requirements.txt open the cmd and the installation is successful! Pro-tested it works, thanks for sharing!

**Comment by YG6688-bit** [comment]
> Many people encounter the same problem when using the portable version of ComfyUI. The issue with the node not showing is unrelated to this repository!
> 
> It occurs because the portable version has its own Python interpreter. If you run `pip install -r requirements.txt`, it will install the packages in your local Python environment, not in the embedded Python within the portable ComfyUI. You need to navigate to the directory where the embedded Python is located and install the packages from there.

**Comment by YG6688-bit** [comment]
Copy the requirements.txt file inside the python path, after copying this command python.exe -m pip install -r requirements.txt open the cmd and the installation is successful! Pro-tested it works, thanks for sharing!

**Comment by 4lt3r3go** [comment]
> Copy the requirements.txt file inside the python path, after copying this command python.exe -m pip install -r requirements.txt open the cmd and the installation is successful! Pro-tested it works, thanks for sharing!

i did this but havent solved

**Comment by ClothingAI** [comment]
Try: https://github.com/cubiq/PuLID_ComfyUI/issues/23

**Comment by balazik** [comment]
@threeforces @cchance27 @4lt3r3go @leonviz87 please see this solution: [https://github.com/balazik/ComfyUI-PuLID-Flux/issues/20#issuecomment-2408536291](https://github.com/balazik/ComfyUI-PuLID-Flux/issues/20#issuecomment-2408536291)

Of course, don’t just copy the links directly; make sure to adjust them according to your portable ComfyUI path.
